---
# Playbook for MySQL servers with replication

- name: copy the my.cnf file
  action: template src=my.cnf.j2 dest={{ mysql_conf_dir }}/my.cnf owner=root mode=0644
  notify: restart mysql

- name: start mysql service
  service: name={{ mysql_service }} state=started enabled=yes

- name: update mysql root password
  command: /usr/bin/mysqladmin -uroot -proot password '{{ mysql_root_db_pass }}'

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600


  # Setup users

- name: ensure anonymous users are not in the database
  mysql_user: name='' state=absent

- name: create the database users
  mysql_user: name={{ item.name }} host={{ item.host }} password={{ item.pass }} priv={{ item.priv }} state=present
  with_items: mysql_users
  when: mysql_users|lower() != 'none'

- name: create the replication users
  mysql_user: name={{ item.name }} host='%' password={{ item.pass }}
                priv=*.*:"REPLICATION SLAVE" state=present
  with_items: mysql_repl_user
  when: mysql_repl_role == 'master'

#
# Create database
#

- name: remove the test database
  action: mysql_db db=test state=absent

- name: create the databases
  mysql_db: name={{ item.name }} state=present
  with_items: mysql_db
  when: mysql_db|lower() != 'none'

#
# Replication settings
#

- name: check if slave is already configured for replication
  mysql_replication: mode=getslave
  ignore_errors: true
  register: slave
  when: mysql_repl_role == 'slave'

- name: get the current master servers replication status
  mysql_replication: mode=getmaster
  delegate_to: "{{ mysql_repl_master }}"
  register: repl_stat
  when: slave|failed and mysql_repl_role == 'slave' and mysql_repl_master is defined

- name: change the master in slave to start the replication
  mysql_replication: >
    mode=changemaster
    master_host={{ mysql_repl_master }}
    master_user={{ mysql_repl_user[0].name }}
    master_password={{ mysql_repl_user[0].pass }}
    master_log_file={{ repl_stat.File }}
    master_log_pos={{ repl_stat.Position }}
  when: slave|failed and mysql_repl_role == 'slave' and mysql_repl_master is defined
  ignore_errors: True

- name: start replication
  mysql_replication: mode=startslave
  when: slave|failed and mysql_repl_role == 'slave' and mysql_repl_master is defined
