---
mysql_service: mysql
mysql_conf_dir: /etc
mysql_slow_log: /var/log/mysqld-slow.log
mysql_port: 3306               
mysql_bind_address: "0.0.0.0"  
mysql_root_db_pass: p@ssw0rd  

mysql_db:                                 
  - name: repdb
    replicate: yes

mysql_users:                              
  - name: repuser
    host: localhost
    pass: repuser
    priv: "repdb.*:ALL"
  - name: repuser
    host: "%"
    pass: repuser
    priv: "repdb.*:ALL"

mysql_repl_user:                          
  - name: repl
    pass: repl
