---
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

# Frontend settings.
haproxy_frontend_name: 'frontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 3306
haproxy_frontend_mode: 'tcp'

# Backend settings.
haproxy_backend_name: 'backend'
haproxy_backend_mode: 'tcp'
haproxy_backend_balance_method: 'roundrobin'

# List of backend servers.
haproxy_backend_servers: []
   - name: mysql0
     address: 192.168.88.200:3306
   - name: mysql1
     address: 192.168.88.201:3306

haproxy_global_vars: []
